name: Combined Insights Processing
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  insight-generation:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.7"
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          repository: investivision/insight-service
          token: ${{ secrets.PAT }}
          ref: "dynamo"
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      - name: generate insights
        run: python main.py
      - name: Archive
        uses: Wandalen/wretry.action@v1.0.11
        with:
          action: peaceiris/actions-gh-pages@v3
          with: |
            personal_token: ${{ secrets.PAT }}
            external_repository: investivision/insight-service
            publish_dir: ./insights
            keep_files: true
            publish_branch: insights
            commit_message: update for all insights
          attempt_limit: 10
